name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Build DEB package
        run: cmake --build build --target package

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: proxy-pattern-deb
          path: build/*.deb
